name: Build DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Visual Studio Build Tools and DirectX SDK
        shell: pwsh
        run: |
          choco install visualstudio2026buildtools `
            --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended" `
            -y
          choco install directx-sdk -y

      - name: Set DirectX SDK environment variables
        shell: pwsh
        run: |
          echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\" >> $GITHUB_ENV
          echo "INCLUDE=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Include;$env:INCLUDE" >> $GITHUB_ENV
          echo "LIB=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86;$env:LIB" >> $GITHUB_ENV

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution x86
        shell: cmd
        run: |
          REM Build using MSBuild for Win32 (x86)
          msbuild D3D9Hook.sln ^
            /p:Configuration=Release ^
            /p:Platform=x86 ^
            /m

      - name: Upload artifact/s
        uses: actions/upload-artifact@v6
        with:
          name: DLL
          path: |
            Win32/Release/*.dll
